name: Build release distributions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:

jobs:

  build-dist:
    name: Build distribution files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: install dependencies
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade build

      - name: create release binaries
        run: |
          python -m build

      - uses: actions/upload-artifact@v7
        with:
          name: dist-files
          path: ./dist/*


  upload_to_pypi:
    name: Upload to PyPI
    needs: [build-dist]
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # this permission is mandatory for trusted publishing
    # if: ${{ github.event_name == 'release' && github.event.action == 'published' }}

    steps:
      - name: Download wheels from cloud runners
        uses: actions/download-artifact@v8
        with:
          name: dist-files
          path: dist
      
      - name: check...
        run: |
          ls -la
          cd dist
          ls -la

      # - uses: pypa/gh-action-pypi-publish@v1.13.0
      #   with:
      #     packages_dir: dist/
